# Generated by Django 5.2.11 on 2026-02-28 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='id',
            field=models.UUIDField(default=uuid.UUID('83928949-a8b2-4829-a278-1ed3cc46d78e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a69ca24-5179-4f15-85c8-6eaa53b81888'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bc051e2-3ae9-4c68-9570-32de0af0336f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facedata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('597185b1-e81b-4f04-929e-c8cf8a1732ed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
